//
//  FeatureFlag+"Orders".swift
//  TouchBistro
//
//  Generated by make package
//
import Foundation
import Platform

enum FeatureFlagKey: String {
    case example
}

enum FeatureFlagProvider {
    private(set) static var provider: Platform.FeatureFlagProvider!
    static func variation(forKey flagKey: FeatureFlagKey, fallback: Bool) -> Bool {
        return Self.provider._variation(forKey: flagKey, fallback: fallback)
    }

    static func setProvider(_ provider: Platform.FeatureFlagProvider) {
        Self.provider = provider
    }
}
