//
//  SettingsCoordinator.swift
//  TouchBistro
//
//  Generated by make package
//

import Platform
import UIKit
import SwiftUI

public class SettingsCoordinator: Coordinator {
    public var navigationController: UINavigationController

    public init(
        navigationController: UINavigationController,
        logger: Platform.Logger,
        featureFlag: Platform.FeatureFlagProvider
    ) {
        self.navigationController = navigationController
        Logger.setLogger(logger)
        FeatureFlag.setProvider(featureFlag)
    }

    public func start() {
        Logger.debug("SettingsCoordinator start")
        let viewModel = SettingsViewModel(router: self)
        let settingsVC = SettingsViewController(viewModel)
        navigationController.pushViewController(settingsVC, animated: true)
    }

    public func stop() {
        Logger.debug("SettingsCoordinator stop")
    }

    deinit {
        Logger.debug("SettingsCoordinator deinit")
    }
}

extension SettingsCoordinator: SettingsRouter {
}
