//
//  FeatureFlag+"Settings".swift
//  TouchBistro
//
//  Generated by make package
//
import Foundation
import Platform

enum FeatureFlagKey: String {
    case example
}

enum FeatureFlagProvider {
    private(set) var provider: Platform.FeatureFlagProvider!
    static func variation(forKey flagKey: FeatureFlagKey, fallback: Bool) -> Bool {
        return _variation(forKey: flagKey, fallback: fallback)
    }

    static func setProvider(_ provider: Self) {
        Self.provider = provider
    }
}
