//
//  FeatureFlag+"Settings".swift
//  TouchBistro
//
//  Generated by make package
//
import Foundation
import Platform

enum FeatureFlagKey: String {
    case example
}

var FeatureFlagProvider: Platform.FeatureFlagProvider!
extension Platform.FeatureFlagProvider {
    func variation(forKey flagKey: FeatureFlagKey, fallback: Bool) -> Bool {
        return _variation(forKey: flagKey, fallback: fallback)
    }

    static func setProvider(_ provider: Self) {
        FeatureFlagProvider = provider
    }
}
